# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-25 16:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleMenuPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(default='1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponibilidad', models.DateField()),
                ('cantidad_maxima', models.IntegerField()),
                ('nombre', models.CharField(max_length=45)),
                ('breve_descripcion', models.CharField(max_length=80)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rango_hora', models.CharField(max_length=13)),
                ('street_number', models.TextField(blank=True, null=True)),
                ('route', models.TextField(blank=True, null=True)),
                ('locality', models.TextField(blank=True, null=True)),
                ('administrative_area_level_2', models.TextField(blank=True, null=True)),
                ('administrative_area_level_1', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('direccion_texto', models.CharField(max_length=100)),
                ('disponible', models.CharField(default='1', max_length=1)),
                ('estado', models.CharField(default='1', max_length=1)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('ingredientes', models.TextField()),
                ('imagen', models.ImageField(upload_to='img-platos/')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPlato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('icono', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='plato',
            name='tipo_plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.TipoPlato'),
        ),
        migrations.AddField(
            model_name='menu',
            name='tipo_entrega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.TipoEntrega'),
        ),
        migrations.AddField(
            model_name='detallemenuplato',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.Menu'),
        ),
        migrations.AddField(
            model_name='detallemenuplato',
            name='plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negocio.Plato'),
        ),
    ]
