# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_auto_20170921_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='lat',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='lng',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
