# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20170920_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
