# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0003_direccion_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='direccion',
            new_name='direccion_texto',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='direccion',
            old_name='longitude',
            new_name='lng',
        ),
    ]
