# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20170921_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='seleccionada',
            field=models.BooleanField(default=False),
        ),
    ]
